service: thecitynook-serverless

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-south-1'}
  profile: thecitynook

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  reservationEnquiry:
    handler: src/handlers/reservationEnquiry.handler
    events:
      - httpApi:
          path: /reservation-enquiry
          method: post
  availableDates:
    handler: src/handlers/availableDates.handler
    events:
      - httpApi:
          path: /available-dates
          method: get
